using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Mvc;
using MediatR;
using Application.Core;

// This class is inherited by all API controllers

namespace API.Controllers
{

    [ApiController]
    [Route("api/[controller]")] // This will name the route after the controller but without "controller".

    public class BaseApiController : ControllerBase
    {
        private IMediator _mediator;

        protected IMediator Mediator => _mediator ??= HttpContext.RequestServices.GetService<IMediator>();    

        //
        // This method allows us to return a Result which is generated by validation in the Application project/layer
        //
        protected ActionResult HandleResult<T>(Result<T> result)
        {            
            if(result == null) return NotFound();
            if(result.IsSuccess && result.Value != null){
                return Ok(result.Value);
            }
            if(result.IsSuccess && result.Value == null){
                return NotFound();            
            }
            return BadRequest(result.Error);
        }
    }
}